name: CI

on:
   push:
     branches:
       - v1.x
       - ci-test
   pull_request:
     branches:
       - v1.x
       
defaults:
  run:
    shell: bash

jobs:
  macOS:
    name: Mac
    needs: []
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        name: [ Release ]
        include:
          - name: Release
            type: Release
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: Install Homebrew dependencies
      run: |
        brew update || true
        brew install qt5 lftp automake
        brew link qt5 --force
    - name: Build
      run: |
        mkdir build
        pushd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.type }} ..
        make -j2
        popd
    - if: matrix.type == 'Release' && github.event_name == 'push'
      name: Preparing for deploy
      run: ./util/buildscripts/scripts/prepare_deps_macos.sh ./build/bin/qrenderdoc.app/Contents/MacOS/qrenderdoc
    - if: matrix.type == 'Release' && github.event_name == 'push'
      name: Packaging artifacts for nightly build
      run: |
        FNAME="RenderDoc_macOS.zip"
        zip -r "${FNAME}" build/bin
        ls -lh "${FNAME}"
        echo "FNAME=$FNAME" >> $GITHUB_ENV
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: RenderDoc_macOS.zip
        asset_name: RenderDoc_macOS.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "RenderDoc MacOSX"
